services:
  - type: web
    name: snov-painel
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SNOV_CLIENT_ID
        sync: false
      - key: SNOV_CLIENT_SECRET
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
